
import_from_git(
  url: "https://gitee.com/panda-eye/fastlane_lanes.git", # 
  branch: "HEAD", # The branch to checkout on the repository.
  path: "UpdateLib/Fastfile", # The path of the Fastfile in the repository.
)